name: CI

on:
  push:
    branches: [ master, develop ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore SharpRNA.sln

    - name: Build Packages
      run: msbuild SharpRNA.sln /p:Configuration=Release

    - name: Run Tests
      run: dotnet test --no-restore --nologo --verbosity minimal
