name: Publish Packages

on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  publish:
    name: Publish Packages
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check for Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        dry_run: true
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup .NET Core
      if: steps.semantic.outputs.new_release_published == 'true'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build Packages
      if: steps.semantic.outputs.new_release_published == 'true'
      run: dotnet build --configuration Release -p:Version=${{ steps.semantic.outputs.new_release_version }} -o packages

    - name: Publish to NuGet
      if: steps.semantic.outputs.new_release_published == 'true'
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Publish to GitHub
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Publish to GitHub
    #   if: steps.semantic.outputs.new_release_published == 'true'
    #   run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/McManning/index.json
